name: clean_code_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  equatable: ^2.0.7
  get_it: ^8.0.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true